### ISSUE TITLE
Pp.dat parse error

### ISSUE THREAD

**Issue by Confusedplayer** [oobol2000oo/RETON#10] opened 2020-08-29 18:58 UTC
Hi, thanks for providing this tool. I hope someone can check how I'm using it. 
1. I copy pp.dat from android to my laptop
2. I run the reton executable file
3. Pp.dat is recognised as a rton file. A new folder is created which contains a json file.
(without editing the json file, to identify at which stage my issue is occurring) 
4. I again run the executable, now producing a .Rton file.
5 I rename this file pp.dat
6 I copy this version of pp.dat back to my android device
7. On attempting to open pvz2, the screen goes black for a few seconds then back to the home screen.
8. On replacing pp.dat with the old version, the app opens as usual

I hope that I've explained that even without editing the json file I'm still experiencing issues. I would appreciate any thoughts or advice. Thanks in advance.

**Comment by h3x4n1um** [comment] 2020-09-04 02:31
I'll take look at if I can reproduce it. Thank you for report bug

**Comment by Confusedplayer** [comment] 2020-09-04 18:34
Thank you. I'm running android 8.0.0 & Windows 10 Pro, and this happens whether I try to edit the json file or just convert pp.dat to json and back again without editing the file.

**Comment by Confusedplayer** [comment] 2020-09-04 18:41
I run rton-json.exe which produces
Rton2json>pp.json

And again to produce
Rton2json>json2rton>pp.rton

If I rename pp.rton to pp.dat and copy it to my android device, pvz2 won't open, but runs fine if I overwrite the new pp.dat with the original pp.dat.

**Comment by h3x4n1um** [comment] 2020-12-02 02:15
I just re-implemented `0x90` and `0x91` bytecode in json2rton. Please wait for 3.1.0 release and see if it fixed

**Comment by h3x4n1um** [comment] 2021-02-05 05:50
3.1.0 is out, please test and report

**Comment by h3x4n1um** [comment] 2021-03-05 06:08
Seems like no further reply, I'm closing this issue until there is new update

**Closed as completed by h3x4n1um** 2021-03-05 06:08 UTC
Labels: bug

**Comment by nineteendo** [comment] 2021-06-07 16:41
I would check this again with any pp.dat, I personally can't test this because I would first have to update Xcode.
